# The URL the site will be built for
base_url = "https://mattiasfest.in"
title = "mattiasfest.in"
description = "Mattias' personal blog"
generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"
extra_grammars = ["syntaxes/math.tmLanguage.json"]

[extra]
# Put all your custom variables here
