#!/usr/bin/env node
/**
 * Extracts the Clippy agent assets from the `clippyjs` package.
 *
 * The published package inlines each agent's sprite sheet as a base64
 * data URI inside a .mjs module - 1.78 MB of JavaScript string for what
 * is really a 1.27 MB PNG, parsed on the main thread and invisible to
 * the image cache. It also ships ten agents we don't want.
 *
 * So we take only what Clippy needs, as real files:
 *
 *   static/clippy/map.png   the sprite sheet, as an actual image
 *   static/clippy/clippy.css  one @keyframes per animation
 *
 * The runtime is dropped entirely. Every Clippy frame is a single
 * background-position (the agent has overlayCount 1, so nothing is ever
 * composited from two layers), which means an animation is just a
 * keyframe track: emit each frame at its cumulative offset, put
 * step-end on the animation so each position holds until the next, and
 * playing one costs a class name. That replaces ~73 kB of runtime plus
 * frame table with ~55 kB of CSS that gzips to ~8 kB, and hands the
 * timing to the compositor instead of a setTimeout chain.
 *
 * What's lost: the runtime's frame branching, which randomly varies and
 * loops the idles. static/clippy.js compensates by choosing a random
 * idle animation rather than branching inside one.
 *
 * Sounds are deliberately dropped: browsers block unprompted audio, and
 * a blog that goes "ding" at you is a worse joke than a silent clip.
 *
 * The stylesheet is big enough that it must stay out of bundle.css and
 * be injected on demand - see static/clippy.js.
 *
 * Run after upgrading clippyjs:  node scripts/gen-clippy.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { PNG } from "pngjs";

const PKG = new URL("../node_modules/clippyjs/dist/", import.meta.url);
const OUT_DIR = new URL("../static/clippy/", import.meta.url).pathname;

mkdirSync(OUT_DIR, { recursive: true });

/* --- Sprite sheet --- */

const mapSrc = readFileSync(new URL("agents/clippy/map.mjs", PKG), "utf8");
const b64 = mapSrc.match(/data:image\/png;base64,([A-Za-z0-9+/=]+)/);
if (!b64) throw new Error("no base64 sprite sheet found in clippy/map.mjs");
const png = Buffer.from(b64[1], "base64");

/* Sanity-check it really is the sheet the frame table indexes into,
   rather than silently shipping a broken background. */
const { width, height } = PNG.sync.read(png);
/* Written through verbatim: upstream already ships it as a 107-color
   palette PNG, and it is better compressed than anything we can
   produce with zlib alone (scripts/optimize-png.mjs measures its own
   repack at ~90 kB worse, and so leaves this file alone). */
writeFileSync(`${OUT_DIR}map.png`, png);

/* --- Animations --> CSS --- */

const { default: agent } = await import(new URL("agents/clippy/agent.mjs", PKG));
const [fw, fh] = agent.framesize;
if (width % fw || height % fh) {
  throw new Error(`sheet ${width}x${height} isn't a whole number of ${fw}x${fh} frames`);
}

/* Percentages are cumulative over the animation's own length, so a
   frame that holds for 800ms and one that flicks past in 10ms both land
   correctly without an even-spacing assumption. */
function track(frames) {
  const total = frames.reduce((sum, f) => sum + (f.duration || 0), 0);
  if (!total) throw new Error("animation with zero total duration");
  const steps = [];
  let elapsed = 0;
  let last = null;
  for (const frame of frames) {
    /* A frame with no images is a deliberate pause: it still advances
       the clock, but step-end means the previous position simply
       holds, so there is nothing to emit. */
    if (frame.images?.length) {
      const [x, y] = frame.images[0];
      const pos = `${-x}px ${-y}px`;
      if (pos !== last) {
        const at = ((elapsed / total) * 100).toFixed(4).replace(/\.?0+$/, "");
        steps.push(`${at || "0"}%{background-position:${pos}}`);
        last = pos;
      }
    }
    elapsed += frame.duration || 0;
  }
  return { steps, total };
}

/* Whatever RestPose starts on is the clip's default, so a freshly shown
   agent isn't a blank box before its first animation runs. */
const restFrame = agent.animations.RestPose.frames[0].images[0];

let css =
  `/* AUTO-GENERATED by scripts/gen-clippy.mjs - do not edit by hand */\n` +
  /* display:block because the sprite is carried by a <span>: an inline
     box would ignore the width/height and collapse to nothing. */
  `.clippy{display:block;width:${fw}px;height:${fh}px;` +
  `background:url("/clippy/map.png") no-repeat ${-restFrame[0]}px ${-restFrame[1]}px;` +
  `image-rendering:pixelated}\n` +
  `.clippy.loop{animation-iteration-count:infinite}\n`;

let keyframes = 0;
for (const [name, anim] of Object.entries(agent.animations)) {
  const { steps, total } = track(anim.frames);
  keyframes += steps.length;
  css += `@keyframes c-${name}{${steps.join("")}}\n`;
  css += `.clippy.a-${name}{animation:c-${name} ${total}ms step-end both}\n`;
}

/* Motion this decorative has no business overriding a stated
   preference; the clip still appears, it just stops flailing. */
css +=
  `@media (prefers-reduced-motion:reduce){` +
  `.clippy,.clippy.loop{animation:none!important}}\n`;

writeFileSync(`${OUT_DIR}clippy.css`, css);

const kb = (n) => (n / 1024).toFixed(1) + " kB";
console.log(
  `✓ clippy: map.png ${width}x${height} (${kb(png.length)}, was ${kb(b64[1].length)} of base64), ` +
    `clippy.css (${kb(css.length)} raw, ${kb(gzipSync(css).length)} gzipped, ` +
    `${Object.keys(agent.animations).length} animations, ${keyframes} keyframes)`
);
