#!/usr/bin/env node
/**
 * Builds the icon sprite sheet used across the site.
 *
 * Reads the Win98 icon PNGs from assets/icons-win98/ (source-only, not
 * deployed) and packs the handful the site actually uses into a single
 * static/icons/sprite.png, plus a generated sass/_icons.scss with one
 * class per icon. One HTTP request instead of a dozen.
 *
 * Also copies the computer icon to static/favicon.png.
 *
 * Run manually after changing the ICONS list:  node scripts/gen-sprite.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PNG } from "pngjs";

const SRC_DIR = new URL("../assets/icons-win98", import.meta.url).pathname;
const SPRITE_OUT = new URL("../static/icons/sprite.png", import.meta.url).pathname;
const SCSS_OUT = new URL("../sass/_icons.scss", import.meta.url).pathname;
const FAVICON_OUT = new URL("../static/favicon.png", import.meta.url).pathname;

/* name → source file. Small icons (≤16px) go on row y=0, 32px icons on
   row y=16. Class names are icon-<name>-<size>. */
const ICONS_SMALL = {
  computer: "computer_explorer-0.png",
  folder: "directory_closed-1.png",
  question: "help_question_mark-1.png",
  channels: "channels-1.png",
  console: "console_prompt-1.png",
  "control-panel": "directory_control_panel-1.png",
  shutdown: "shut_down_normal-1.png",
  notepad: "notepad-0.png",
  error: "msg_error-2.png",
  flag: "windows-3.png", // 14x14, Start button
};

const ICONS_LARGE = {
  computer: "computer_explorer-2.png",
  folder: "directory_closed-0.png",
  question: "help_question_mark-0.png",
  error: "msg_error-0.png",
  warning: "msg_warning-0.png",
};

const SMALL_ROW_H = 16;

function load(file) {
  return PNG.sync.read(readFileSync(join(SRC_DIR, file)));
}

const placements = [];
let x = 0;
for (const [name, file] of Object.entries(ICONS_SMALL)) {
  const png = load(file);
  if (png.height > SMALL_ROW_H) throw new Error(`${file} too tall for the small row`);
  placements.push({ name: `${name}-${png.width}`, png, x, y: 0 });
  x += png.width;
}
const smallWidth = x;
x = 0;
for (const [name, file] of Object.entries(ICONS_LARGE)) {
  const png = load(file);
  if (png.width !== 32 || png.height !== 32) {
    throw new Error(`${file} is ${png.width}x${png.height}, expected 32x32`);
  }
  placements.push({ name: `${name}-32`, png, x, y: SMALL_ROW_H });
  x += 32;
}

const width = Math.max(smallWidth, x);
const height = SMALL_ROW_H + 32;
const sprite = new PNG({ width, height });

for (const p of placements) {
  PNG.bitblt(p.png, sprite, 0, 0, p.png.width, p.png.height, p.x, p.y);
}

writeFileSync(SPRITE_OUT, PNG.sync.write(sprite));
writeFileSync(FAVICON_OUT, readFileSync(join(SRC_DIR, ICONS_LARGE.computer)));

let scss = `/* AUTO-GENERATED by scripts/gen-sprite.mjs - do not edit by hand */

.icon {
  display: inline-block;
  flex-shrink: 0;
  background: url("/icons/sprite.png") no-repeat;
  image-rendering: pixelated;
}
`;
for (const p of placements) {
  scss += `
.icon-${p.name} {
  width: ${p.png.width}px;
  height: ${p.png.height}px;
  background-position: ${p.x === 0 ? "0" : `-${p.x}px`} ${p.y === 0 ? "0" : `-${p.y}px`};
}
`;
}
writeFileSync(SCSS_OUT, scss);

console.log(`✓ sprite.png (${width}x${height}, ${placements.length} icons) + _icons.scss + favicon.png`);
